-- Migration 0.99.1 → 0.99.2: SPARQL/Datalog view decode=true IVM fix (issue #81)
--
-- Schema changes: None.
--
-- Rust changes:
--   * compile_sparql_for_view() no longer wraps the stream table SQL with
--     dictionary decode subqueries.  The stream table always stores BIGINT
--     dictionary IDs, keeping pg_trickle IVM on the integer delta path.
--   * create_sparql_view() / create_datalog_view(): when decode = true, a
--     companion VIEW {name}_decoded is created on top of the stream table
--     (same pattern as create_construct_view / create_framing_view).
--   * drop_sparql_view() / drop_datalog_view(): also DROP the _decoded
--     companion view if it exists.
